package qap;

public enum ESAType {
	BASIC_SA, CONNOLLY_SA, COSINE_SA, MODIFIED_SA, GEOMETRIC_SA, LIST_BASED_SA, 
	GEOMETRIC_TA,
	GEOMETRIC_NM, 
	GREAT_DELUGE,
	ROBUST_TABOO_SEARCH,
	FAST_ANT_SYSTEM, HYBRID_ANT_SYSTEM, ONE_PLUS_ONE_ANT_ALGORITHM
}
