package qap;

public enum ETestType {
	SINGLE_INSTANCE_SINGLE_ALGORITHM, 
	SINGLE_INSTANCE_MULTIPLE_ALGORITHM,
	MULTIPLE_INSTANCE_SINGLE_ALGORITHM, 
	MULTIPLE_INSTANCE_MULTIPLE_ALGORITHM,
	PARAMETER_BEGIN_TEMPERATURE_TUNNING,
	PARAMETER_FINAL_TEMPERATURE_TUNNING
}
